<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>InfoSolar</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&amp;display=swap">
    <link rel="stylesheet" href="assets/css/Stats-icons.css">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-md sticky-top py-3" id="mainNav">
        <div class="container"><a class="navbar-brand d-flex align-items-center" href="/"><span class="bs-icon-sm bs-icon-circle bs-icon-primary shadow d-flex justify-content-center align-items-center me-2 bs-icon"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-bookshelf">
                        <path d="M2.5 0a.5.5 0 0 1 .5.5V2h10V.5a.5.5 0 0 1 1 0v15a.5.5 0 0 1-1 0V15H3v.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 .5-.5zM3 14h10v-3H3v3zm0-4h10V7H3v3zm0-4h10V3H3v3z"></path>
                    </svg></span><span>InfoSolar</span></a><button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item"><a class="nav-link" href="index.php">Calculator</a></li>
                    <li class="nav-item"><a class="nav-link" href="concept.php">Concept</a></li>
                    <li class="nav-item"><a class="nav-link active" href="information.php">Information</a></li>
                </ul><a class="btn btn-primary shadow" role="button" href="index.php">Magic</a>
            </div>
        </div>
    </nav>
    <section class="py-5">
        <div class="container py-5">
            <div class="row mb-5">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <p class="fw-bold text-success mb-2">Information</p>
                    <h2 class="fw-bold">Solar Panels</h2>
                    <p class="fw-bold mb-2" style="color: var(--bs-blue);">Solar Panels are a great asset to renewable energies. They offer great benefits, but are also costly and last for only 25 years. This potentially means you will need to dispose of them down the line. In any house considering Solar Panels, choosing to install them for economic reasons is a bad idea if you're not planning to live in the house for at least 8 years. Yet, Solar Panels also add great value to the house due to their versatility in summer months to enable you to go off-grid.</p>
                    <picture><img src="assets/img/1.jpg" style="width: 80%;padding: 2px;"></picture>
                    <h2 class="fw-bold">Batteries</h2>
                    <p class="fw-bold mb-2" style="color: var(--bs-blue);">Solar batteries are energy storage systems that store excess energy generated by solar panels. They offer benefits such as reducing reliance on the grid, providing a backup power source, and contributing to a more sustainable energy system. However, their financial benefits depend on various factors, and they can be expensive to purchase and install. Therefore, investing in solar batteries requires careful consideration and planning.</p>
                    <picture><img src="assets/img/4.jpg" style="width: 80%;padding: 2px;"></picture>
                    <h2 class="fw-bold">Low Budget Solar Panels</h2>
                    <p class="fw-bold mb-2" style="color: var(--bs-blue);">There are many downsides to low budget solar panel setups include lower energy output, reduced durability, and potentially higher maintenance costs. Low budget solar panels may also not be as effective in capturing and converting sunlight into electricity, which may result in lower overall energy savings.</p>
                    <picture><img src="assets/img/2.jpg" style="width: 80%;padding: 2px;"></picture>
                    <h2 class="fw-bold">Low Budget Batteries</h2>
                    <p class="fw-bold mb-2" style="color: var(--bs-blue);">Low budget batteries for solar energy storage are available in the market at lower prices than high-end batteries. These batteries may be less expensive to purchase and install, but they may have lower capacity, shorter lifespan, and may not perform as well as higher-end batteries.</p>
                    <picture><img src="assets/img/5.jpg" style="width: 80%;padding: 2px;"></picture>
                    <h2 class="fw-bold">Obstruction of Solar Panels</h2>
                    <p class="fw-bold mb-2" style="color: var(--bs-blue);">Obstruction of sunlight can significantly impact the performance and efficiency of solar panels. When solar panels are shaded or partially obstructed, they produce less electricity or may even stop producing electricity altogether.</p>
                    <picture><img src="assets/img/6.jpg" style="width: 80%;padding: 2px;"></picture>
                </div>
            </div>
        </div>
    </section>
    <footer class="bg-dark">
        <div class="container py-4 py-lg-5">
            <hr>
            <div class="text-muted d-flex justify-content-between align-items-center pt-3">
                <p class="mb-0">Designed for Raspberry PI competition 2023</p>
                <ul class="list-inline mb-0">
                    <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right-short">
                            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"></path>
                        </svg></li>
                    <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right-short">
                            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"></path>
                        </svg></li>
                    <li class="list-inline-item"><svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" fill="currentColor" viewBox="0 0 16 16" class="bi bi-arrow-right-short">
                            <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"></path>
                        </svg></li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/bold-and-dark.js"></script>
</body>

</html>
